# Generated by Django 3.2.22 on 2023-10-20 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descrip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descrip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descrip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appcultura.area')),
                ('idempresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appcultura.empresa')),
                ('idepar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SectorEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descrip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TamEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('cedula', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.IntegerField(default=1)),
                ('idcargo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appcultura.cargo')),
                ('idempresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appcultura.empresaareas')),
                ('idrol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appcultura.roluser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descrip', models.TextField()),
                ('idcargo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appcultura.cargo')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='idgrupoem',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.grupoempresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='idsector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appcultura.sectorempresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='idtam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appcultura.tamempresa'),
        ),
    ]
