# Generated by Django 3.2.22 on 2023-11-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperfil',
            name='idcargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.cargo'),
        ),
        migrations.AlterField(
            model_name='userperfil',
            name='idempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.empresaareas'),
        ),
        migrations.AlterField(
            model_name='userperfil',
            name='idrol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.roluser'),
        ),
    ]
