# Generated by Django 3.2.22 on 2023-11-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0003_curso_sesioncurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descrip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sesioncurso',
            name='lugar',
            field=models.CharField(max_length=255),
        ),
    ]
