# Generated by Django 3.2.22 on 2023-11-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0004_auto_20231109_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivosCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.TextField()),
                ('competencias', models.TextField()),
                ('idcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.curso')),
            ],
        ),
    ]
