# Generated by Django 3.2.22 on 2023-11-15 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0005_objetivoscurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kpiarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descrip', models.TextField()),
                ('fechaini', models.DateTimeField()),
                ('fechafin', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('idemparea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.empresaareas')),
            ],
        ),
        migrations.CreateModel(
            name='Kpiobjetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objtivo', models.TextField()),
                ('meta', models.TextField()),
                ('indicador', models.TextField()),
                ('idkpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.kpiarea')),
            ],
        ),
    ]
