# Generated by Django 3.2.22 on 2023-11-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0006_kpiarea_kpiobjetivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaareas',
            name='idarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.area'),
        ),
        migrations.AlterField(
            model_name='empresaareas',
            name='idempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.empresa'),
        ),
        migrations.AlterField(
            model_name='empresaareas',
            name='idepar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.departamento'),
        ),
    ]
