# Generated by Django 4.2.7 on 2023-11-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0006_alter_empresa_idgrupoem_alter_empresa_idsector_and_more'),
        ('appcultura', '0007_auto_20231115_1652'),
    ]

    operations = [
    ]
