# Generated by Django 3.2.22 on 2023-11-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0008_merge_20231116_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemasSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.TextField(null=True)),
                ('competencias', models.TextField(null=True)),
                ('recursos', models.CharField(max_length=255, null=True)),
                ('idsesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.sesioncurso')),
            ],
        ),
    ]
