# Generated by Django 3.2.22 on 2023-11-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0009_temassesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='temassesion',
            name='ruta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='temassesion',
            name='recursos',
            field=models.TextField(null=True),
        ),
    ]
