# Generated by Django 3.2.22 on 2023-11-18 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0008_merge_20231116_1723'),
        ('appcultura', '0010_auto_20231117_1421'),
    ]

    operations = [
    ]
