# Generated by Django 4.2.7 on 2023-11-18 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0011_merge_20231117_2001'),
        ('appcultura', '0011_merge_20231117_2004'),
    ]

    operations = [
    ]
