# Generated by Django 3.2.22 on 2023-11-22 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0012_grupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruposCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.curso')),
                ('idgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.grupos')),
            ],
        ),
    ]
