# Generated by Django 3.2.22 on 2023-11-22 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0013_gruposcursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruposUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.grupos')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.userperfil')),
            ],
        ),
    ]
