# Generated by Django 3.2.22 on 2023-11-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0012_merge_20231117_2019'),
        ('appcultura', '0014_gruposuser'),
    ]

    operations = [
    ]
