# Generated by Django 4.2.7 on 2023-11-24 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0015_merge_0012_merge_20231117_2019_0014_gruposuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia', models.DateTimeField(auto_now_add=True)),
                ('idsesioncurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.sesioncurso')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.userperfil')),
            ],
        ),
    ]
