# Generated by Django 4.2.5 on 2023-11-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0017_formulario_preguntas_opciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='opciones',
            name='correcta',
            field=models.BooleanField(default=False),
        ),
    ]
