# Generated by Django 4.2.7 on 2023-11-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0017_calificaionusuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalificaionUsuarios',
            new_name='CalificacionUsuarios',
        ),
    ]
