# Generated by Django 4.2.7 on 2023-12-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0018_rename_calificaionusuarios_calificacionusuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionusuarios',
            name='comentario_valor_curso',
            field=models.TextField(null=True),
        ),
    ]
