# Generated by Django 4.2.7 on 2023-12-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0019_calificacionusuarios_comentario_valor_curso'),
        ('appcultura', '0019_preguntas_valor'),
    ]

    operations = [
    ]
