# Generated by Django 4.2.5 on 2023-12-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0020_merge_20231204_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
                ('idform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.formulario')),
                ('idsesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.sesioncurso')),
            ],
        ),
    ]
