# Generated by Django 4.2.5 on 2023-12-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0021_sesionformulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(null=True)),
                ('tipores', models.CharField(max_length=255)),
                ('valores', models.IntegerField(null=True)),
                ('comentario', models.TextField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaenvio', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecharevision', models.DateTimeField(null=True)),
                ('idpreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.preguntas')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.userperfil')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False)),
                ('idopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.opciones')),
                ('idres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.respuestaform')),
            ],
        ),
    ]
