# Generated by Django 4.2.7 on 2023-12-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0022_rename_id_sesion_curso_compromisos_id_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisos',
            name='estado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='compromisos',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.curso'),
        ),
        migrations.AlterField(
            model_name='compromisos',
            name='prioridad',
            field=models.TextField(),
        ),
    ]
