# Generated by Django 4.2.7 on 2023-12-08 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0024_remove_compromisos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisos',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.userperfil'),
        ),
        migrations.AlterField(
            model_name='compromisos',
            name='con_quien',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='compromisos',
            name='id_estado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appcultura.estadocompromisos'),
        ),
    ]
