# Generated by Django 4.2.7 on 2023-12-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0025_compromisos_id_usuario_alter_compromisos_con_quien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisos',
            name='respuesta',
            field=models.TextField(null=True),
        ),
    ]
