# Generated by Django 4.2.7 on 2023-12-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0023_respuestaform_idsesion'),
        ('appcultura', '0026_compromisos_respuesta'),
    ]

    operations = [
    ]
