# Generated by Django 4.2.7 on 2023-12-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0027_merge_20231212_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='pendiente',
            field=models.BooleanField(null=True),
        ),
    ]
