# Generated by Django 4.2.7 on 2023-12-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0029_sesionasistencia_asistencia_pendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionasistencia',
            name='asistencia_pendiente',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
