# Generated by Django 3.2.22 on 2023-12-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0028_auto_20231212_2202'),
        ('appcultura', '0030_alter_sesionasistencia_asistencia_pendiente'),
    ]

    operations = [
    ]
