# Generated by Django 3.2.22 on 2023-12-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0031_merge_20231214_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcompetencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.competencias')),
                ('idcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcultura.curso')),
            ],
        ),
    ]
