# Generated by Django 3.2.22 on 2024-02-01 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0032_competenciacurso_competencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperfil',
            name='idcargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.cargo'),
        ),
        migrations.AlterField(
            model_name='userperfil',
            name='idempresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.empresaareas'),
        ),
    ]
