# Generated by Django 3.2.22 on 2024-02-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0033_auto_20240201_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpiarea',
            name='idemparea',
        ),
        migrations.RemoveField(
            model_name='userperfil',
            name='idempresa',
        ),
        migrations.AddField(
            model_name='area',
            name='idempresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.empresa'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='idarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.area'),
        ),
        migrations.AddField(
            model_name='kpiarea',
            name='idarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.area'),
        ),
        migrations.AddField(
            model_name='userperfil',
            name='idepart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.departamento'),
        ),
        migrations.DeleteModel(
            name='EmpresaAreas',
        ),
    ]
