# Generated by Django 3.2.22 on 2024-02-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0035_kpiarea_idepar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objcargo',
            name='idcargo',
        ),
        migrations.RemoveField(
            model_name='userperfil',
            name='idcargo',
        ),
        migrations.AddField(
            model_name='userperfil',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='ObjCargo',
        ),
    ]
