# Generated by Django 3.2.22 on 2024-02-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0036_auto_20240212_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='idarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.area'),
        ),
    ]
