# Generated by Django 3.2.22 on 2024-02-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0037_userperfil_idarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormadorEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.empresa')),
                ('idusu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.userperfil')),
            ],
        ),
    ]
