# Generated by Django 3.2.22 on 2024-02-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0038_formadorempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='formadorempresa',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
