# Generated by Django 3.2.22 on 2024-02-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0040_auto_20240214_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='idempresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.empresa'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='idusu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.userperfil'),
        ),
    ]
