# Generated by Django 3.2.22 on 2024-02-16 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0042_auto_20240216_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacionusuarios',
            old_name='id_usuario',
            new_name='idusuario',
        ),
        migrations.CreateModel(
            name='CalificacionFormador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claridad', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('capacidad', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('dominio', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('aspectosrescatar', models.TextField(null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('formador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_emitidas', to='appcultura.userperfil')),
                ('sesion_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.sesioncurso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recibidas', to='appcultura.userperfil')),
            ],
        ),
    ]
