# Generated by Django 3.2.22 on 2024-03-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0043_auto_20240216_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceCompromisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaini', models.DateField(auto_now=True)),
                ('fechafin', models.DateField()),
                ('actividad', models.TextField()),
                ('estado', models.TextField()),
                ('puntaje', models.IntegerField(default=0)),
                ('respuesta', models.TextField(null=True)),
                ('idcompromiso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.compromisos')),
                ('idusurespuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.userperfil')),
            ],
        ),
    ]
