# Generated by Django 3.2.22 on 2024-03-21 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0044_avancecompromisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechasCompromisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechadd', models.DateField(auto_now=True)),
                ('idcompromiso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.compromisos')),
            ],
        ),
    ]
