# Generated by Django 3.2.22 on 2024-06-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0046_alter_fechascompromisos_fechadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='idempresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.empresa'),
        ),
    ]
