# Generated by Django 3.2.22 on 2024-07-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0048_userperfil_idempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacionformador',
            name='sesion_curso',
        ),
        migrations.RemoveField(
            model_name='calificacionusuarios',
            name='id_sesiones_curso',
        ),
        migrations.AddField(
            model_name='calificacionformador',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.curso'),
        ),
        migrations.AddField(
            model_name='calificacionusuarios',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appcultura.curso'),
        ),
    ]
