# Generated by Django 3.2.22 on 2024-10-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0049_auto_20240702_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(max_length=50)),
                ('expires_in', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('scope', models.TextField()),
            ],
        ),
    ]
