# Generated by Django 3.2.22 on 2024-10-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcultura', '0050_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='vpass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
